name: Publish rehype-custom-code to npm

on:
  push:
    paths: ["packages/rehype-custom-code/**"]
    tags:
      - v*
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build package
        run: bun run build
        working-directory: packages/rehype-custom-code

      - name: Test package
        run: bun run test
        working-directory: packages/rehype-custom-code

      - name: publish `rehype-custom-code` to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
